project:
  type: website

website:
  title: "craigrshenton"
  site-url: https://craig-shenton.github.io/craigrshenton
  repo-url: https://github.com/craig-shenton/craigrshenton
  favicon: assets/favicons/Rubics_Cube.svg
  twitter-card: true
  open-graph: true
  navbar:
    background: light
    title: false
    collapse-below: lg
    left:
      - text: "Blog"
        aria-label: home
        icon: "rss"
        href: index.qmd
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/craig-shenton
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/craigrshenton/
format:
  html:
    theme: 
      light: 
        - litera
        - custom.scss
    smooth-scroll: true



