project:
  type: website

website:
  title: "craigrshenton"
  site-url: https://craig-shenton.github.io/craigrshenton
  repo-url: https://github.com/craig-shenton/craigrshenton
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/craig-shenton
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/craigrshenton/
format:
  html:
    theme: 
      light: 
        - litera
        - custom.scss
      dark:
        - slate
        - custom.scss
    smooth-scroll: true



