---
title: "Data Engineering Links"
description: "Data Engineering key concepts, tools, and best practices."
date: "2023-04-08"
categories: []
---

## Databases
- [Do You Need A Data Warehouse - A Quick Guide - Seattle Data Guy](https://www.theseattledataguy.com/do-you-need-a-data-warehouse-a-quick-guide/#page-content) 
- [What's a Data Vault Model and How to Implement It on the Databricks Lakehouse Platform - The Databricks Blog](https://www.databricks.com/blog/2023/02/24/data-vault-best-practice-implementation-lakehouse.html) 
- [Composable OLAP](https://blog.fal.ai/composable-olap/) 
- [QuestDB  Fast SQL for time-series](https://questdb.io/) 
- [Prequel - Data syncs & data warehouse integration](https://www.prequel.co/) 

## Projects

- [Project A Data Modelling Best Practices Part I: How to Model Data in a Data Warehouse? - YouTube](https://www.youtube.com/watch?v=8HlNG8bdlM0) 
- [(500) Project A Data Modelling Best Practices Part II: How to Build a Data Warehouse? - YouTube](https://www.youtube.com/watch?v=24Uvo5vZJWA)
- [Designing a Data Project to Impress Hiring Managers - Start Data Engineering](https://www.startdataengineering.com/post/data-engineering-project-to-impress-hiring-managers/) 
- [Build Data Engineering Projects, with Free Template - Start Data Engineering](https://www.startdataengineering.com/post/data-engineering-projects-with-free-template/) 
- [Data Engineering Project for Beginners - Batch edition - Start Data Engineering](https://www.startdataengineering.com/post/data-engineering-project-for-beginners-batch-edition/) 
- [Data engineering projects with template: Airflow, dbt, Docker, Terraform (IAC), Github actions (CI/CD) & more : dataengineering](https://www.reddit.com/r/dataengineering/comments/ygieh8/data_engineering_projects_with_template_airflow/) 
- [GitHub - DataTalksClub/data-engineering-zoomcamp: Free Data Engineering course!](https://github.com/DataTalksClub/data-engineering-zoomcamp) 
- [A data engineering project with Prefect, Docker, Terraform, Google CloudRun, BigQuery and Streamlit  by Ryan Lamb  Mar, 2023  Medium](https://medium.com/@ryanelamb/a-data-engineering-project-with-prefect-docker-terraform-google-cloudrun-bigquery-and-streamlit-3fc6e08b9398) 
- [eliasbenaddouidrissi](https://eliasbenaddouidrissi.dev/posts/data_engineering_project_monzo/) 
- [GitHub - RSKriegs/finnhub-streaming-data-pipeline: Stream processing pipeline from Finnhub websocket using Spark, Kafka, Kubernetes and more](https://github.com/RSKriegs/finnhub-streaming-data-pipeline) 
- [GitHub - ankurchavda/streamify: A data engineering project with Kafka, Spark Streaming, dbt, Docker, Airflow, Terraform, GCP and much more!](https://github.com/ankurchavda/streamify) 
- [GitHub - ABZ-Aaron/Reddit-API-Pipeline](https://github.com/ABZ-Aaron/Reddit-API-Pipeline) 
- [GitHub - ris-tlp/audiophile-e2e-pipeline: Pipeline that extracts data from Crinacle's Headphone and InEarMonitor databases and finalizes data for a Metabase Dashboard.](https://github.com/ris-tlp/audiophile-e2e-pipeline) 
- [GitHub - dominikhei/Local-Data-LakeHouse: Sample Data Lakehouse deployed in Docker containers using Apache Iceberg, Minio, Trino and a Hive Metastore. Can be used for local testing.](https://github.com/dominikhei/Local-Data-LakeHouse) 

## Pipelines

- [Data Pipeline Design Patterns - #1. Data flow patterns - Start Data Engineering](https://www.startdataengineering.com/post/design-patterns/) 
- [stevecrox0914 comments on ETL using pandas](https://www.reddit.com/r/dataengineering/comments/zr2klf/etl_using_pandas/j1324sh/)
- [Minimally Sufficient Pandas. In this article, I will offer an...  by Ted Petrou  Dunder Data  Medium](https://medium.com/dunder-data/minimally-sufficient-pandas-a8e67f2a2428) 
- [(756) Building a robust data pipeline with dbt, Airflow, and Great Expectations - YouTube](https://www.youtube.com/watch?v=9iN6iw7Lamo)  
- [Real-time Data Processing and Analysis with Kafka, Connect, KSQL, Elasticsearch, and Flask  by Stefentaime  Feb, 2023  Medium](https://medium.com/@stefentaime_10958/real-time-data-processing-and-analysis-with-kafka-connect-ksql-elasticsearch-and-flask-f55366032d78) 

### Orchestration

- [Leverage Azure Databricks jobs orchestration from Azure Data Factory - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/analytics-on-azure-blog/leverage-azure-databricks-jobs-orchestration-from-azure-data/ba-p/3123862) 
- [Introducing Databricks Workflows - The Databricks Blog](https://www.databricks.com/blog/2022/05/10/introducing-databricks-workflows.html) 
- [Dagster vs. Airflow  Dagster Blog](https://dagster.io/blog/dagster-airflow) 

### Spark

- [Introduction to Pyspark join types - Blog  luminousmen](https://luminousmen.com/post/introduction-to-pyspark-join-types) 
- [The 5-minute guide to using bucketing in Pyspark - Blog  luminousmen](https://luminousmen.com/post/the-5-minute-guide-to-using-bucketing-in-pyspark) 
- [Spark tips. DataFrame API - Blog  luminousmen](https://luminousmen.com/post/spark-tips-dataframe-api) 
- [Spark core concepts explained - Blog  luminousmen](https://luminousmen.com/post/spark-core-concepts-explained) 

### dbt

- [dbt - Transform data in your warehouse](https://www.getdbt.com/)
- [(702) Introduction to dbt (data build tool) from Fishtown Analytics - YouTube](https://www.youtube.com/watch?v=M8oi7nSaWps)
- [Learn exactly how to use dbt™ in a modern data workflow  Course](https://www.kahandatasolutions.com/the-playbook-for-dbt) 
- [dbt(Data Build Tool) Tutorial - Start Data Engineering](https://www.startdataengineering.com/post/dbt-data-build-tool-tutorial/)
- [corp/dbt_style_guide.md at main - dbt-labs/corp - GitHub](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md) 
- [Populate dbt models with CSV data. Part 2: the power of dbt-fal](https://blog.fal.ai/populate-dbt-models-with-csv-data-part-2-the-power-of-dbt-fal/) 
- [DBT Core & Airflow. Empowering our data organization with...  by Albert Franzi  Albert Franzi  Medium](https://medium.com/albert-franzi/dbt-core-airflow-7d94edac9cdf) 

### Kubernetes

- [What is Kubernetes used for in data engineering? : dataengineering](https://www.reddit.com/r/dataengineering/comments/rja8s6/what_is_kubernetes_used_for_in_data_engineering/) 

### Data Lake

- [Big Data file formats - Blog  luminousmen](https://luminousmen.com/post/big-data-file-formats) 
- [Lakehouse --- A resumé  by Robert Kossendey  claimsforce](https://medium.com/claimsforce/lakehouse-a-resum%C3%A9-750368e57914) 
- [Parquet: more than just "Turbo CSV"](https://csvbase.com/blog/3) 

## Testing

- [Cleaning sample data in standardized way  Crystal Lewis](https://cghlewis.com/blog/data_clean_03/?utm_source=substack&utm_medium=email) 
- [The Unreasonable Effectiveness of Data Pipeline Smoke Tests  Dagster Blog](https://dagster.io/blog/smoke-test-data-pipeline) 
- [Introduction to the Pipeline Data Validation Workflow (VALID-II) - pointblank](https://rich-iannone.github.io/pointblank/articles/VALID-II.html) 
- [How to Use Great Expectations in Databricks  Great Expectations](https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_in_databricks/) 
- [GitHub - gladykov/chain.train: ETL & database testing framework for big data, written with Python, using Pytest. With connectors for Spark, Snowflake, MySQL/MariaDB.](https://github.com/gladykov/chain.train/)
- [Test data generation: There and back](https://www.synthesized.io/post/test-data-generation-there-and-back)
- [How To Test Your Data With Great Expectations  DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-test-your-data-with-great-expectations) 
- [pytest tips and tricks  pythontest](https://pythontest.com/pytest-tips-tricks/)

## Data Quality

- [How to use dbt-expectations to detect data quality issues](https://www.datafold.com/blog/dbt-expectations) 
- [Data Quality Dimensions: Assuring Your Data Quality with Great Expectations - KDnuggets](https://www.kdnuggets.com/2023/03/data-quality-dimensions-assuring-data-quality-great-expectations.html) 
- [Test data quality at scale with Deequ  AWS Big Data Blog](https://aws.amazon.com/blogs/big-data/test-data-quality-at-scale-with-deequ/) 
- [DEEQU, I mean Data Quality. We say how we can turn the world upside...  by Ajith Shetty  Medium](https://ajithshetty28.medium.com/deequ-i-mean-data-quality-a0e6c048469d) 
- [Unit Testing Data at Scale using Deequ and Apache Spark](https://www.velotio.com/engineering-blog/test-data-quality-at-scale-using-deequ-and-apache-spark) 
- [Guaranteeing Data Quality SLAs with Deequ & Databand - YouTube](https://www.youtube.com/watch?v=D29txlJyBvk) 

## CI/CD

- [E5: Building Better CI/CD Pipelines - by Marius Kimmina](https://www.infrastructureposts.com/p/e5-building-better-cicd-pipelines) 
- [Continuous Delivery - YouTube](https://www.youtube.com/@ContinuousDelivery/videos) 
- [2022 State of DevOps Report    Google Cloud](https://cloud.google.com/devops/state-of-devops) 
- [Continuous Deployment or Continuous Delivery?  When To Release - YouTube](https://www.youtube.com/watch?v=mBzDPRgue6s) 

## Documentation

- [The importance of a handbook-first approach to documentation  GitLab](https://about.gitlab.com/company/culture/all-remote/handbook-first-documentation/) 
- [What is Continuous Documentation? The Manifesto Part I](https://swimm.io/blog/what-is-continuous-documentation-manifesto-part-1/?utm_source=IPE_circuit&utm_medium=paid_pub&utm_campaign=IPE-march&utm_content=gm-test) 

## Managment

- [Modern data engineering playbook](https://www.thoughtworks.com/content/dam/thoughtworks/documents/e-book/tw_ebook_modern_data_engineering_playbook.pdf)
- [GitHub - andkret/Cookbook: The Data Engineering Cookbook](https://github.com/andkret/Cookbook) 
- [Data Team  GitLab](https://about.gitlab.com/handbook/business-technology/data-team/) 
- [My Facebook Bootcamp Experience](https://mukulrathi.com/facebook-bootcamp-experience/) 
- [Writing an engineering strategy.  Irrational Exuberance](https://lethain.com/eng-strategies/) 
- [The Art and Science of Measuring Data Teams Value  Airbyte](https://airbyte.com/blog/measuring-data-teams-value) 
- [DORA Four Key Metrics (Accelerate book) - Measuring Engineering Productivity](https://www.engprod.guide/docs/dora-four-key-metrics-accelerate-book) 
- [Agile Is A Glass Cannon --- Tom Dalling](https://www.tomdalling.com/blog/software-processes/agile-is-a-glass-cannon/) 
- [Using architectural decision records to streamline technical decision-making for a software development project - AWS Prescriptive Guidance](https://docs.aws.amazon.com/prescriptive-guidance/latest/architectural-decision-records/welcome.html) 
- [Jsonnet - The Data Templating Language](https://jsonnet.org/) 

## Observability

- [If data lineage is the answer, what is the question?  by Gabs Ferreira  Alvin  Mar, 2023  Medium](https://medium.com/alvin-ai/if-data-lineage-is-the-answer-what-is-the-question-bad7f5f44fb5) 
- [Modern Data Strategy: Quality, Observability, Cataloging and Lineage  by Danilo Drobac  Feb, 2023  Medium](https://medium.com/@danilo.drobac/modern-data-strategy-quality-observability-cataloging-and-lineage-45ef492771b)

## Analytics

- [Pouria Hadjibagheri and the UK's abandoned open data revolution  The Spectator](https://www.spectator.co.uk/article/pouria-hadjibagheri-and-the-uks-abandoned-open-data-revolution/) 
- [How The Post is replacing Mapbox with open source solutions - Kevin Schaul](https://www.kschaul.com/post/2023/02/16/how-the-post-is-replacing-mapbox-with-open-source-solutions/) 
- [GitHub - protomaps/protomaps.js: Lightweight vector map rendering, labeling and symbology for the web](https://github.com/protomaps/protomaps.js) 

## Follow

- [(756) Seattle Data Guy - YouTube](https://www.youtube.com/@SeattleDataGuy) 
- [Deep Channel - Tools for the data craft.](https://www.deepchannel.com/) 
- [Andreas Kretz - YouTube](https://www.youtube.com/channel/UCY8mzqqGwl5_bTpBY9qLMAA) 
- [Kahan Data Solutions - YouTube](https://www.youtube.com/c/kahandatasolutions) 
- [The Developing Dev  Ryan Peterman  Substack](https://www.developing.dev/) 
- [Data Engineering: Posts  LinkedIn](https://www.linkedin.com/showcase/skills-data-engineering/posts/?feedView=all) 
- [Quastor  Quastor Tech  Substack](https://quastor.substack.com/?nthPub=24) 

## Career

- [A Senior Engineer's Guide to the System Design Interview  interviewing.io](https://interviewing.io/guides/system-design-interview/part-two#concepts-apis) 
- [GitHub - jithendray/dp203-azure-data-engineering: notes for DP203-Data Engineering on Azure](https://github.com/jithendray/dp203-azure-data-engineering) 

## Data Science

- [Faker library in python - An intriguing expedient for data scientists  by Sanjay Nandakumar  Towards Data Science](https://towardsdatascience.com/faker-library-in-python-an-intriguing-expedient-for-data-scientists-7dd06f953050) 

## Security
- [5 Ways for Enterprise Teams to Secure Their DevOps Pipelines in 2023](https://devm.io/devops/devops-pipelines-security)

## Python
- [Automate your Python project with Makefile](https://antonz.org/makefile-automation/)

## SQL

- [Harold Sinnott #MWC23 on Twitter: "Best of #SQL Cheat Sheet](https://twitter.com/HaroldSinnott/status/1637559588231806977/photo/1) 
- [SQLBolt - Learn SQL - Introduction to SQL](https://sqlbolt.com/) 

## Learn

- [Exam DP-203: Data Engineering on Microsoft Azure - Certifications  Microsoft Learn](https://learn.microsoft.com/en-us/certifications/exams/dp-203/) 
- [Learn MS SQL Server & PostgreSQL: Database Design A-Z™  Udemy](https://www.udemy.com/course/sqldatabases/?ranMID=39197&ranEAID=GjbDpcHcs4w&ranSiteID=GjbDpcHcs4w-PUSFwymG6hWEeJK4omaHXw&LSNPUBID=GjbDpcHcs4w&utm_source=aff-campaign&utm_medium=udemyads) 
- [Ultimate AWS Certified Solutions Architect Associate (SAA)  Udemy](https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/?LSNPUBID=GjbDpcHcs4w&ranEAID=GjbDpcHcs4w&ranMID=39197&ranSiteID=GjbDpcHcs4w-WwMLJrOGOzPYaIxBnd3xQw&utm_medium=udemyads&utm_source=aff-campaign) 
- [The Complete SQL Bootcamp for the Manipulation and Analysis of Data  Udemy](https://www.udemy.com/course/the-complete-sql-bootcamp/?ranMID=39197&ranEAID=HTtUFxqit0c&ranSiteID=HTtUFxqit0c-4gKQS74XfsAh.IZSlqreSA&LSNPUBID=HTtUFxqit0c&utm_source=aff-campaign&utm_medium=udemyads) 
- [Linux for Beginners: Linux Basics  Udemy](https://www.udemy.com/course/linux-for-beginners-2021/?ranMID=39197&ranEAID=HTtUFxqit0c&ranSiteID=HTtUFxqit0c-DuIubHb12wJSCBhhkJ.YLQ&LSNPUBID=HTtUFxqit0c&utm_source=aff-campaign&utm_medium=udemyads) 
- [Data Warehouse Fundamentals for Beginners  Udemy](https://www.udemy.com/course/data-warehouse-fundamentals-for-beginners/?ranMID=39197&ranEAID=HTtUFxqit0c&ranSiteID=HTtUFxqit0c-9yFtjfjjGG9Hb2iBfrIPWg&LSNPUBID=HTtUFxqit0c&utm_source=aff-campaign&utm_medium=udemyads) 
- [Spark and Python for Big Data with PySpark  Udemy](https://www.udemy.com/course/spark-and-python-for-big-data-with-pyspark/?ranMID=39197&ranEAID=HTtUFxqit0c&ranSiteID=HTtUFxqit0c-Pbp3UMxUqvLxanBaqwTPJg&LSNPUBID=HTtUFxqit0c&utm_source=aff-campaign&utm_medium=udemyads) 
- [The Complete Hands-On Introduction to Apache Airflow  Udemy](https://www.udemy.com/course/the-complete-hands-on-course-to-master-apache-airflow/?ranMID=39197&ranEAID=HTtUFxqit0c&ranSiteID=HTtUFxqit0c-J6iO3LtbOFBDGXT2lH5dUA&LSNPUBID=HTtUFxqit0c&utm_source=aff-campaign&utm_medium=udemyads) 
- [[8 Course BUNDLE]: DP-203: Data Engineering on MS Azure  Udemy](https://www.udemy.com/course/implementing-real-world-use-cases-in-azure-data-factory-v2/?ranMID=39197&ranEAID=HTtUFxqit0c&ranSiteID=HTtUFxqit0c-hziIO3LSO84o8wc3_JYtrw&LSNPUBID=HTtUFxqit0c&utm_source=aff-campaign&utm_medium=udemyads) 
- [BI Analysis: MySQL for Data Analytics and Business Intelligence  Udemy](https://www.udemy.com/course/sql-mysql-for-data-analytics-and-business-intelligence/?ranMID=39197&ranEAID=GjbDpcHcs4w&ranSiteID=GjbDpcHcs4w-d4YWyAls6bMMAhmDcmEN1g&utm_source=aff-campaign&LSNPUBID=GjbDpcHcs4w&utm_medium=udemyads) 
- [Docker & Kubernetes: The Practical Guide- [2023 Edition]  Udemy](https://www.udemy.com/course/docker-kubernetes-the-practical-guide/?ranMID=39197&ranEAID=GjbDpcHcs4w&ranSiteID=GjbDpcHcs4w-7ellSaNnSbyL6hGq9tSvag&LSNPUBID=GjbDpcHcs4w&utm_source=aff-campaign&utm_medium=udemyads) 
- [Data Warehouse - The Ultimate Guide  Udemy](https://www.udemy.com/course/data-warehouse-the-ultimate-guide/?ranMID=39197&ranEAID=GjbDpcHcs4w&ranSiteID=GjbDpcHcs4w-ivsJYgXfpWSS23Z3otILXg&LSNPUBID=GjbDpcHcs4w&utm_source=aff-campaign&utm_medium=udemyads) 
- [Practice Exams  AWS Certified Solutions Architect Associate  Udemy](https://www.udemy.com/course/practice-exams-aws-certified-solutions-architect-associate/?src=sac&kw=aws&ranMID=39197&ranEAID=GjbDpcHcs4w&ranSiteID=GjbDpcHcs4w-pZEYq01OMjucejKWZqCn.w&LSNPUBID=GjbDpcHcs4w&utm_source=aff-campaign&utm_medium=udemyads) 

## Misc

- [What is Data Engineering? - The Pragmatic Engineer](https://blog.pragmaticengineer.com/what-is-data-engineering/?utm_source=substack&utm_medium=email) 
- [If You Only Read A Few Data Articles In 2023, Read These  by Sven Balnojan  Geek Culture  Feb, 2023  Medium](https://medium.com/geekculture/if-you-only-read-a-few-data-articles-in-2023-read-these-c589a00c763d) 
- [Low Code Software Development Is A Lie](https://jaylittle.com/post/view/2023/4/low-code-software-development-is-a-lie)
- [blog/we-need-a-new-versioning-notation.md at main - davidbullado/blog - GitHub](https://github.com/davidbullado/blog/blob/main/we-need-a-new-versioning-notation.md) 

## Uncategorised (todo)
- [Welcome  Superset](https://superset.apache.org/)
- [Library Genesis](https://libgen.li/index.php) 
- [Apache Iceberg](https://iceberg.apache.org/) 
- [confusables - PyPI](https://pypi.org/project/confusables/) 
- [fal - Features & Labels](https://fal.ai/) 
- [Earthly CI: Launching a new era for CI - Earthly Blog](https://earthly.dev/blog/launching-earthly-ci/) 
- [Pricing  Tabular](https://tabular.email/pricing) 
- [pydantic-factories - PyPI](https://pypi.org/project/pydantic-factories/) 
- [Vault by HashiCorp](https://www.vaultproject.io/) 
- [digitalghost-dev (Christian) - GitHub](https://github.com/digitalghost-dev)
- [GitHub - andrem8/surf_dash](https://github.com/andrem8/surf_dash) 
- [GitHub - context-labs/autodoc: Toolkit for auto-generating codebase documentation using LLMs](https://github.com/context-labs/autodoc) 
- [Jsonnet - The Data Templating Language](https://jsonnet.org/) 
- [Mountpoint for S3 : dataengineering](https://www.reddit.com/r/dataengineering/comments/125cd6n/mountpoint_for_s3/) 
- [Data Quality Dimensions: Assuring Your Data Quality with Great Expectations - KDnuggets](https://www.kdnuggets.com/2023/03/data-quality-dimensions-assuring-data-quality-great-expectations.html) 

- [SQLMesh](https://sqlmesh.com/) 
- [Comparisons - SQLMesh](https://sqlmesh.readthedocs.io/en/stable/comparisons/#complexity) 
- [Soda Core - Data Reliability Engineering as Code](https://www.soda.io/core) 

- [How to Join a fact and a type 2 dimension (SCD2) table - Start Data Engineering](https://www.startdataengineering.com/post/how-to-join-fact-scd2-tables/) 
- [Perspective  Perspective](https://perspective.finos.org/) 
- [5 Helpful Extract & Load Practices for High-Quality Raw Data  by Sven Balnojan  Apr, 2023  Towards Data Science](https://towardsdatascience.com/5-helpful-extract-load-practices-for-high-quality-raw-data-65b9a59a8721) 
- [CDC in Production: An Operating Guide](https://materialize.com/guides/cdc-in-production/) 
- [Implementing Data Contracts at GoCardless  Tech @ GoCardless](https://medium.com/gocardless-tech/implementing-data-contracts-at-gocardless-3b5c49074d13) 
- [A complete Apache Airflow tutorial: building data pipelines with Python  AI Summer](https://theaisummer.com/apache-airflow-tutorial/) 
- [GitHub - getdozer/dozer: Connect any data source, combine them in real-time and instantly get low-latency Data APIs. All with just a simple configuration!](https://github.com/getdozer/dozer) 
- [Dozer  Start building real-time data apps in minutes  Dozer  Start building real-time data apps in minutes](https://getdozer.io/) 
- [DevOps uses a capability model, not a maturity model - Octopus Deploy](https://octopus.com/blog/devops-uses-capability-not-maturity) 
- [ddanieltan.com - How to add some personality to your Quarto Blog](https://www.ddanieltan.com/posts/blogtips/) 

- [Tech Dive - APIs - by Quastor Tech - Quastor](https://quastor.substack.com/p/-tech-dive-apis) 
- [Tech Dive - APIs PART 2 - by Quastor Tech - Quastor](https://quastor.substack.com/p/-tech-dive-apis-part-2) 
- [Tech Dive - Database Sharding - by Quastor Tech - Quastor](https://quastor.substack.com/p/-tech-dive-database-sharding) 
- [Learn System Design? - by Quastor Tech - Quastor](https://quastor.substack.com/p/-learn-system-design) 
- [The Metaverse - by Quastor Tech - Quastor](https://quastor.substack.com/p/-the-metaverse) 
- [Software Architecture in the Real World - by Quastor Tech](https://quastor.substack.com/p/-software-architecture-in-the-real) 
- [Docker Explained - by Quastor Tech - Quastor](https://quastor.substack.com/p/-docker-explained-13d) 
- [The Architecture Behind the World's Largest Developer Site...](https://quastor.substack.com/p/-the-architecture-behind-the-worlds) 
- [Tech Dive - APIs - by Quastor Tech - Quastor](https://quastor.substack.com/p/tech-dive-apis) 
- [The Engineering Behind Facebook Newsfeed](https://quastor.substack.com/p/-the-engineering-behind-facebook) 
- [Distributed Databases Explained - by Quastor Tech](https://quastor.substack.com/p/-distributed-databases-explained) 
- [Khan Academy's migration from Python to Go](https://quastor.substack.com/p/khan-academys-migration-from-python) 
- [A summary of Clean Code - by Quastor Tech - Quastor](https://quastor.substack.com/p/-writing-clean-code) 
- [Clean Code - Part 2 - by Quastor Tech - Quastor](https://quastor.substack.com/p/clean-code-part-2) 
- [Clean Code - Part 3 - by Quastor Tech - Quastor](https://quastor.substack.com/p/clean-code-part-3) 
- [How WhatsApp scaled to 1 billion users with only 50 engineers](https://quastor.substack.com/p/how-whatsapp-scaled-to-1-billion) 
- [The Architecture of Databases - by Quastor Tech - Quastor](https://quastor.substack.com/p/the-architecture-of-databases) 
- [Principles for API Design - by Quastor Tech - Quastor](https://quastor.substack.com/p/principles-for-api-design) 
- [How Notion sharded their Postgres Database](https://quastor.substack.com/p/how-notion-sharded-their-postgres) 
- [How GitHub shifted from a Monolith to Microservices](https://quastor.substack.com/p/githubs-shift-from-monolith-to-microservices) 
- [Partitioning Relational Databases at GitHub](https://quastor.substack.com/p/partitioning-relational-databases) 
- [Software Architecture Principles - by Quastor Tech](https://quastor.substack.com/p/software-architecture-principles) 
- [An Introduction to Big Data Architectures - by Quastor Tech](https://quastor.substack.com/p/an-introduction-to-big-data-architectures) 
- [Why LinkedIn changed their tech stack - by Quastor Tech](https://quastor.substack.com/p/why-linkedin-changed-their-tech-stack) 
- [How Khan Academy Rewrote their Backend - by Quastor Tech](https://quastor.substack.com/p/how-khan-academy-rewrote-their-backend) 
- [How Distributed Databases work - by Quastor Tech - Quastor](https://quastor.substack.com/p/how-distributed-databases-work) 
- [Clean Code's Advice on Comments - by Quastor Tech - Quastor](https://quastor.substack.com/p/clean-codes-advice-on-comments) 
- [The Architecture of Databases - by Quastor Tech - Quastor](https://quastor.substack.com/p/the-architecture-of-databases-ba6) 
- [Observability at Twitter - by Quastor Tech - Quastor](https://quastor.substack.com/p/observability-at-twitter) 
- [Airbnb's Architecture - by Quastor Tech - Quastor](https://quastor.substack.com/p/airbnbs-architecture) 
- [How to Design Better APIs - by Quastor Tech - Quastor](https://quastor.substack.com/p/how-to-design-better-apis) 
- [Reliability Engineering at BlackRock - by Quastor Tech](https://quastor.substack.com/p/reliability-engineering-at-blackrock) 
- [Design Docs at Google](https://www.industrialempathy.com/posts/design-docs-at-google/) 
- [How Notion Sharded Their Postgres Database](https://blog.quastor.org/p/notion-sharded-postgres-database-8af4) 
- [How WhatsApp scaled to 1 billion users with only 50 engineers](https://blog.quastor.org/p/whatsapp-scaled-1-billion-users-50-engineers) 
- [Explaining the mechanics of Spark caching - Blog  luminousmen](https://luminousmen.com/post/explaining-the-mechanics-of-spark-caching) 
- [Choosing the Right AWS Storage Service: A Comprehensive Guide to S3, S3N, and S3A - Blog  luminousmen](https://luminousmen.com/post/choosing-the-right-aws-storage-service-a-comprehensive-guide-to-s3-s3n-and-s3a) 
- [Making CI workflow faster with Github Actions - Blog  luminousmen](https://luminousmen.com/post/making-ci-workflow-faster-with-github-actions) 
- [Quality is the responsibility of the team - Blog  luminousmen](https://luminousmen.com/post/quality-is-the-responsibility-of-the-team) 
- [Rumbling about Test Driven Development - Blog  luminousmen](https://luminousmen.com/post/rumbling-about-test-driven-development) 
- [Drunk Post: Things I've learned as a Sr Engineer- [reddit] - Blog  luminousmen](https://luminousmen.com/post/drunk-post-things-ive-learned-as-a-sr-engineer) 
- [First rule of the leader - grow people - Blog  luminousmen](https://luminousmen.com/post/first-rule-of-the-leader) 
- [Change Data Capture (CDC) - Blog  luminousmen](https://luminousmen.com/post/change-data-capture) 
- [ACID vs BASE: Comparison of two Design Philosophies - Blog  luminousmen](https://luminousmen.com/post/acid-vs-base-comparison-of-two-design-philosophies) 
- [Operational Challenges in Big Data - Blog  luminousmen](https://luminousmen.com/post/operational-challenges-in-big-data) 
- [Analytical Challenges in Big Data - Blog  luminousmen](https://luminousmen.com/post/analytical-challenges-in-big-data) 
- [Architecturally Significant Requirements - Blog  luminousmen](https://luminousmen.com/post/architecturally-significant-requirements) 
- [Management Challenges in Big Data - Blog  luminousmen](https://luminousmen.com/post/management-challenges-in-big-data) 
- [Data Challenges in Big Data - Blog  luminousmen](https://luminousmen.com/post/data-challenges-in-big-data) 
- [Soft Skills guide for Software Engineer - Blog  luminousmen](https://luminousmen.com/post/soft-skills-guide-for-software-engineer) 
- [Modern Big Data Architectures - Lambda & Kappa - Blog  luminousmen](https://luminousmen.com/post/modern-big-data-architectures-lambda-kappa) 
- [Guidelines for business meetings - Blog  luminousmen](https://luminousmen.com/post/guidelines-for-business-meetings) 
- [Airflow dag dependencies - Blog  luminousmen](https://luminousmen.com/post/airflow-dag-dependencies) 
- [Clean up your digital hygiene - Blog  luminousmen](https://luminousmen.com/post/clean-up-your-digital-hygiene) 
- [Data Engineering skills - Blog  luminousmen](https://luminousmen.com/post/data-management-skills) 
- [Kubernetes 101 - Blog  luminousmen](https://luminousmen.com/post/kubernetes-101) 
- [Data Lake vs Data Warehouse - Blog  luminousmen](https://luminousmen.com/post/data-lake-vs-data-warehouse) 
- [Python resource limitation - Blog  luminousmen](https://luminousmen.com/post/python-resource-limitation) 
- [The ultimate Python style guidelines - Blog  luminousmen](https://luminousmen.com/post/the-ultimate-python-style-guidelines) 





 
- [Stay SaaSy  Keeping it SaaSy](https://staysaasy.com/) 
- [SLS Letter from Dean](https://law.stanford.edu/wp-content/uploads/2023/03/Next-Steps-on-Protests-and-Free-Speech.pdf?mkt_tok=ODg0LUZTQi0zMDcAAAGKqNfmUfz2S_PCzkgUjCQGrC2DR1ji-TGeKtn3NnnIoJpAduaZaZdKteNsL5dGzCkk5cwWC_6vm8autYIUyUQO4uIJy6lLbBGo47NHk8_3iTA) 


